INSERT INTO companies (id, name, logo_url) VALUES (1,'NovaTech Solutions', 'https://cdn.icon-icons.com/icons2/4019/PNG/512/exploration_cosmonaut_suit_space_jobs_professions_astronaut_icon_255728.png');
INSERT INTO companies (id, name, logo_url) VALUES (2,'Quantum Innovations', 'https://cdn.icon-icons.com/icons2/4019/PNG/512/profession_professions_job_suit_businessman_jobs_icon_255749.png');;
INSERT INTO companies (id, name, logo_url) VALUES (3,'Summit Enterprises', 'https://cdn.icon-icons.com/icons2/4019/PNG/512/thule_guardian_hair_black_jobs_professions_policeman_icon_255730.png');
INSERT INTO companies (id, name, logo_url) VALUES (4,'Horizon Industries', 'https://cdn.icon-icons.com/icons2/4019/PNG/512/jobs_professions_caucasian_sports_aquatic_hair_brown_diver_icon_255754.png');
INSERT INTO companies (id, name, logo_url) VALUES (5,'FusionTech Solutions', 'https://cdn.icon-icons.com/icons2/4019/PNG/512/camouflage_army_military_soldier_icon_255771.png');

INSERT INTO advertisements VALUES (1,'Marketing Manager', 'We are seeking a Senior Software Engineer to join our dynamic team. You will work on cutting-edge projects, collaborate with a talented group of developers, and contribute to the development of innovative software solutions.',1,2200,'123 Tech Street',94101,'San Francisco','7 hours');
INSERT INTO advertisements VALUES (2,'Marketing Coordinator', 'We are looking for a Marketing Coordinator to support our marketing team in executing campaigns, analyzing data, and coordinating various marketing activities. Join us and be part of a dynamic and creative marketing environment.We are looking for a Marketing Coordinator to support our marketing team in executing campaigns, analyzing data, and coordinating various marketing activities. Join us and be part of a dynamic and creative marketing environment.',2,3000,'456 Marketing Avenue',10001,'New York','8 hours');
INSERT INTO advertisements VALUES (3,'Graphic Designer', 'Join our design team as a Graphic Designer and bring your creativity to life. You ''ll be responsible for producing eye-catching visual content and collaborating on exciting design projects.',2,1500,'789 Marketing Avenue',90001,'Los Angeles','6 hours');
INSERT INTO advertisements VALUES (4,'Customer Support Specialist', 'If you''re a problem solver with excellent communication skills, we want you to join our Customer Support team. Help our customers with their inquiries and provide top-notch assistance.',3,4000,'456 Design Street',60601,'Chicago','7 hours');
INSERT INTO advertisements VALUES (5,'Data Analyst', 'Join our team as a Data Analyst and work with large datasets to extract valuable insights. You''ll play a crucial role in making data-driven decisions and driving our company''s success.solutions.',4,3000,'23 Support Street',77001,'Houston','7 hours');
INSERT INTO advertisements VALUES (6,'Registered Nurse', 'Join our nursing team at CareHealth Hospital. We''re looking for compassionate and skilled Registered Nurses to provide exceptional patient care.',2,2200,' 789 Data Way', 98101,'Seattle','7 hours');
INSERT INTO advertisements VALUES (7,'Web Developer', 'We are hiring a Web Developer to create and maintain cutting-edge websites and web applications. Join our team and work on exciting web projects.',1,980,'456 Sales Street',33101,' Miami','3 hours');
INSERT INTO advertisements VALUES (8,'Human Resources Manager', 'We are seeking a Human Resources Manager to lead our HR team. You''ll play a key role in attracting, retaining, and developing our talented workforce.',2,1500,'323 Health Avenue',02101,'Boston','7 hours');
INSERT INTO advertisements VALUES (9,'Senior Software Engineer', 'We are seeking a Senior Software Engineer to join our dynamic team. You will work on cutting-edge projects, collaborate with a talented group of developers, and contribute to the development of innovative software solutions.',3,3000,'789 Web Road',92101,'San Diego','7 hours');

